### ISSUE TITLE
Neovim's intro screen won't appear after installing this plugin

### ISSUE THREAD

**Issue by WieeRd** [Yggdroot/indentLine#342] opened 2021-01-17 06:29 UTC
What I mean by 'intro screen' is the screen you see after launching vim, showing infos like "type :q<Enter> to exit".  
After installing indentLine, that screen doesn't appear anymore and I only see a blank space.  
If I run 'nvim -u NONE' or remove indentLine from plugin list, intro screen appears again.  
It's not a really big issue, but it's still a bug so I wanted to inform you.

I'm using Neovim, and vim-plug as plugin manager. Everything is up to date, using the latest stable version.
This issue happens both on Windows 10 and Manjaro Linux.

**Comment by Yggdroot** [comment] 2021-01-17 10:50
duplicate of #315

**Closed** 2021-01-19 04:21 UTC
