### ISSUE TITLE
Using the plugin results in an empty welcome screen

### ISSUE THREAD

**Issue by ndavidpsi** [Yggdroot/indentLine#334] opened 2020-11-25 18:48 UTC
**This happens in both Vim and Nvim**
_This is my welcome screen before installing the plugin:_
![before](https://user-images.githubusercontent.com/73792104/100270067-69ddd680-2f4f-11eb-85d2-a46b71cb8882.PNG)
_This is after:_
![after](https://user-images.githubusercontent.com/73792104/100270118-7b26e300-2f4f-11eb-81c5-d988eaa05b79.PNG)

**PS: All I did was enter _nvim_ in the command line, no key presses afterwards.**

**Comment by Yggdroot** [comment] 2020-11-27 02:10
duplicate of #315 .

**Closed by Yggdroot** 2020-11-27 02:10 UTC
