### ISSUE TITLE
quotation in JSON files disappears

### ISSUE THREAD

**Issue by johannes-jansson** [Yggdroot/indentLine#255] opened 2018-10-22 12:05 UTC
indentLine has a strange side effect for me: it hides all quotation in json files. Attaching an example with an almost clean vimrc to demonstrate the issue:

With the plugin enabled:
![image](https://user-images.githubusercontent.com/7166848/47291046-91407780-d602-11e8-8830-9292f8c6d6c7.png)

With the plugin disabled:
![image](https://user-images.githubusercontent.com/7166848/47291085-addcaf80-d602-11e8-8154-a7d6fcca884d.png)

The screenshots above were done with this minimal vimrc:
```
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#rc()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-sensible'
Plugin 'yggdroot/indentline'
```

On osx 10.12.6 in iTerm 2 3.2.3, zsh 5.5.1 and Vim 8.1

With my regular vimrc it looks like this:
![image](https://user-images.githubusercontent.com/7166848/47291236-30fe0580-d603-11e8-9ddb-4e19057ad1e6.png)

**Comment by visualdensity** [comment] 2018-10-23 22:40
Same for me too. +1

**Comment by Yggdroot** [comment] 2018-10-23 23:42
Duplicate of #140.

**Closed** 2018-10-24 04:02 UTC
