### ISSUE TITLE
vim listchars (namely whitespace chars) hide the indent line char

### ISSUE THREAD

**Issue by koroliov** [Yggdroot/indentLine#211] opened 2017-05-29 23:06 UTC
It all had been working normally until the other day I updated plugins (I have only two by the way: YouCompleteMe and IndentLines).

Now when I open a file, there is no indent lines and nothing helps: neither IndentLinesDisable/Enable, nor IndentLinesToggle, Reset etc. This is how it looks:
![screenshot_1](https://cloud.githubusercontent.com/assets/1567580/26645543/07f158ca-4641-11e7-8a81-8c9312b7d2dc.png)

But when I split the window, in the left window (the old one) I see, the indent lines characters, but the list chars highlighting is broken (this was an issue since I started to use IndentLines and it was OK for me, cause I usually called my own function `:call ResetHighlightJS()`, where I manually reset syntax and called IndentLinesDisable, then IndentLinesEnable. In the new window everything remains the same as it was before the split. This is how it looks
![screenshot_2](https://cloud.githubusercontent.com/assets/1567580/26645558/12dfd400-4641-11e7-8329-aafa5b4fe5e0.png)

~~I suppose that Vim draws the list chars after IndentLine finishes its work, and on a split Vim does not redraw the list chars, while IndentLine does.~~

No, I tried to disable the list and listchars options and the indent line still isn't visible. The same thing, when I open a file no indent lines are visible. If I split the window, in the left window I see the indent lines.

How can I fix this, that is to be able to see intent lines after I open a file and with normal list chars colors?

Thank you in advance.

I have this version of Vim: `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 17 2017 12:13:35)`

**Comment by koroliov** [comment] 2017-05-30 00:37
Currently I fixed it by rolling back to commit 0c003ed7588a2579a5212b5195336eff3bc59358. I suspected that it was broken in the next commit "Providing new option g:indentLine_setConceal"

**Comment by Yggdroot** [comment] 2017-05-30 02:16
I can not reproduce it. Please use the latest version and have a try.

**Comment by koroliov** [comment] 2017-05-30 02:27
@Yggdroot , what do you mean by the latest version? I was using the latest version (at least I was using the Vunlde plugin to install indentLines. I'm sure Vundle performed necessary actions to update the repository.

Then I decided to rollback to a point, when it definitely was working for me. I looked into the commit history and decided to rollback to the commit I mentioned and everything has become as it was before my last update of the plugins.

As additional info I can say that I'm using the Terminator terminal on Ubuntu 17.04 and Vim 8.0 (the default one from the packages). I don't think that this is a problem of the terminal, since the default Ubuntu terminal gives the same results.

I use only two plugins: indentLine and YouCompleteMe.

**Comment by koroliov** [comment] 2017-05-30 04:39
Now I'm sure this was broken in commit  86b9824b89cf52d4b748ea2a27885607c98c881a because, when I checked out to it the issue appeared anew. I looked into the commit itself, there seems to be not so much changes, but now I cannot tell what exactly broke the highlight.

**Comment by koroliov** [comment] 2017-05-30 04:53
Sorry, I'm closing this issue, since when I updated to the latest commit and removed (actually I don't remember whether it was there before, or I put it myself) the option `let g:indentLine_setConceal = 1` everything has become normal.

**Comment by koroliov** [comment] 2017-05-30 19:23
It seems that I was a bit confused when I closed the issue. It does exist, so I'm reopening it.

It has been broken in commit 2ceee22d25961dcc217eadbdffe6a4b043655d13 "refactor the code fix issue #193" . Until that commit everything had been working fine.

**Comment by koroliov** [comment] 2017-05-30 19:23
It seems that I was a bit confused when I closed the issue. It does exist, so I'm reopening it.

It has been broken in commit 2ceee22 "refactor the code fix issue #193" . Until that commit everything had been working fine.

**Comment by koroliov** [comment] 2017-05-30 23:18
It was broken in the file `bundle/indentLine/after/plugin/indentLine.vim`. After I removed the section in the `IndentLineEnable` function ( `if g:indentLine_newVersion` …. `endif`) indent lines became visible.

I suppose there is some error with the added code. I had the latest commit pulled, `echo indentLine_newVersion` gave 1. At the same time I was not able to call the function `SetConcealOption` from a Vim editing session. Neither `SetConcealOption`, nor `call SetConcealOption()` were succesfull, with errors respectively `not an editor command` and `unknown function`. I think it is strange.

`IndentLinesDisable` still doesn't work, but I'm sure, if I remove the same section ( `if g:indentLine_newVersion` …. `endif`), it will.

Could anyone please suggest something?

**Comment by koroliov** [comment] 2017-05-31 00:09
currently I fixed it by manually setting `let g:indentLine_newVersion = 0` in the vimrc file

**Comment by Yggdroot** [comment] 2017-05-31 02:57
Can you give the minimal vimrc and steps to reproduce it?

**Comment by koroliov** [comment] 2017-05-31 03:36
@Yggdroot , hi, thank you, this is the minimal `vimrc`, where the issue can be reproduced. I suppose there is some problem with the `hi WhiteSpaceChar …` and `call matchadd("WhiteSpaceChar"…` lines, because without them everything works fine. I deliberately made big indents on two lines, in order to be able to see the issue in the same `vimrc` file.

With this `vimrc` file everything does work, but if you change `indentLine_newVersion` to 1, then it breaks.

    set nocompatible              " be iMproved, required
    filetype off                  " required

    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()

      Plugin 'Yggdroot/indentLine'

    call vundle#end()            " required
    filetype plugin indent on    " required

                                set listchars=eol:¬,tab:>-,extends:>,precedes:<,space:·
                                set list
    hi WhiteSpaceChar ctermfg=251 guifg=#999999
    call matchadd("WhiteSpaceChar", "[ \t]")

    let g:indentLine_color_term = 251
    let g:indentLine_newVersion = 0

**Comment by Yggdroot** [comment] 2017-05-31 05:03
```
hi WhiteSpaceChar ctermfg=251 guifg=#999999
call matchadd("WhiteSpaceChar", "[ \t]")
```
These two lines conflict with the plugin, because the new version of plugin also uses `matchadd`.
Why do you use these two lines since there is already `set listchars`?
Also, you can set `let g:indentLine_leadingSpaceEnabled = 1` in vimrc to achieve the same effect.
Actually, these two lines did not take effect at all, even though you did not install indentLine. `ctermfg` and `guifg` are used to set the colors of foreground, but whitespace has no foreground, only the background.

It's not the bug of this plugin, please remove these two useless lines.

**Comment by koroliov** [comment] 2017-05-31 17:36
@Yggdroot , I suppose you are wrong about these lines. I put them there in order to change highlighting of the white spaces and tabs, which are visible with my settings as the `·` and `>-` chars. White spaces in this case have both background and foreground. Their foreground is the `·` char and background is what is behind the char. 

The option indentLine_leadingSpaceEnabled = 1 doesn't give the same effect, since, even if it is possible (I'm not sure about that) to change the char from `˰` to `·` it does not change the other visible spaces in a file, and it looks a bit irritating (you can see all the spaces after : on line 4):
![screenshot](https://cloud.githubusercontent.com/assets/1567580/26645301/3a3d4010-4640-11e7-852c-fff11c0be858.png)

So could you elaborate why do you consider those lines useless. I'm not a Vim script expert, but I'm sure that I found them in some reliable source about how to customize highlighting in Vim and there is nothing wrong with the instructions.

**Comment by Yggdroot** [comment] 2017-06-01 03:25
I did not know that you use those two lines to work with `set listchars` together, I was wrong.
If you want to customize the color of listchars, you can try this:
`hi SpecialKey ctermfg=251 guifg=#999999`, there is no need to use those two lines.

**Comment by koroliov** [comment] 2017-06-01 18:09
@Yggdroot , the SpecialKeys group has some unsolvable problems with the CursorLine group, like this:

![qtu5f](https://cloud.githubusercontent.com/assets/1567580/26693615/746421d2-470d-11e7-91e8-94e01ba5ef2e.png)

The problem is unsolvable according to an authoritative answer on [vi.stackexchange.com](https://vi.stackexchange.com/questions/7924/specialkey-foreground-color-w-cursorline-set/#answer-7926)

Thank you for the suggestion, but I'm going to stick with the old version, it worked well for me and I don't think that something might happen there for it to stop working. If I master vim script to a satisfactory level, I'll try to something better with this.

Should I close the issue now?

**Comment by Yggdroot** [comment] 2017-06-02 02:24
I got your concern. 
Let's close the issue.

**Closed by Yggdroot** 2017-06-02 02:24 UTC
