### ISSUE TITLE
Blank line continuations?

### ISSUE THREAD

**Issue by la-la-lasagna** [Yggdroot/indentLine#288] opened 2020-01-05 18:53 UTC
Hello Devs,

This isn't truly an issue but I wanted to bring it up and see if implementation was easy.

For those coding languages which can have blank lines between lines of code (c++ for instance) I find that the break in the line levels is very annoying.  Would it be possible to continue the indentation symbol on a blank line iff both the above and below line have indentation at that level?  I have a feeling that one issue with this is that your plugin visually alters blank (but used) spaces in the document, and that you cannot do the same visual trick for empty spaces.

Let me know and have a good day!

**Comment by Yggdroot** [comment] 2020-01-07 02:06
This is a duplicate of issue #25.

**Closed** 2020-01-08 08:47 UTC
