### ISSUE TITLE
Why the indentLine is not available in the MacOS terminal, but in Mac Vim it is ok?

### ISSUE THREAD

**Issue by lijiaqiang1988926** [Yggdroot/indentLine#251] opened 2018-09-27 09:45 UTC

**Comment by MindTooth** [comment] 2018-10-18 08:44
Care to maybe elaborate more on your setup?

Terminal.app?  Font?  Custom color scheme?  Etc.?

**Comment by ekaj2** [comment] 2018-11-20 20:08
I just installed this with Pathogen (cloning into `.vim/bundle`) and got the same thing that the OP seems to have. In MacVim, the commands exist (e.g., `IndentLinesToggle`), whereas in the Vim (8.0) in iTerm2 it appears that I did not install it at all. I am using a variation of the Agnoster theme in zsh with patched PowerLine fonts and pretty much a stock MacVim IIRC. However, the plugin doesn't actually appear to do anything even in MacVim.

<img width="891" alt="screen shot 2018-11-20 at 3 04 56 pm" src="https://user-images.githubusercontent.com/20780097/48799617-a679f600-ecd5-11e8-86bd-99789fadb873.png">

<img width="828" alt="screen shot 2018-11-20 at 3 06 02 pm" src="https://user-images.githubusercontent.com/20780097/48799683-cd382c80-ecd5-11e8-9225-b3b41d61ac80.png">

**Comment by ekaj2** [comment] 2018-11-20 20:09
I am thinking that the issue is that the terminal Vim was not compiled with the `conceal` option, while my MacVim was. However, this doesn't explain what I'm seeing (or not seeing) in MacVim. I should probably start a new issue about that...

**Comment by Yggdroot** [comment] 2018-12-02 02:39
Duplicate of issue #59.

**Comment by ekaj2** [comment] 2018-12-02 03:19
@Yggdroot I don't think my issue with MacVim is a duplicate, but the others not compiled with the `conceal` option probably are.

**Comment by ekaj2** [comment] 2018-12-03 02:35
```vim
:hi conceal
Conceal        xxx ctermfg=239 guifg=#2C313A

:echo &concealcursor
inc

:echo &conceallevel
2

```

**Comment by Yggdroot** [comment] 2018-12-03 02:51
@ekaj2 I think it's because that the color of Conceal(guifg=#2C313A) is similar with the color of your background(`hi Normal`)  and it difficult to distinguish between them by eyes.
Please have a try: `hi conceal guifg=Red`

**Comment by ekaj2** [comment] 2018-12-03 02:53
@Yggdroot Bingo. Thanks for the help.

**Closed** 2018-12-03 13:05 UTC
